# -*- coding: utf-8 -*-
"""asighment grop .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9_FiO3bsaW6Tx7lPz1rM4JEtNsgR5CS
"""

import requests

def check_sql_injection(url):
    try:
        # Make the request to the URL
        response = requests.get(url)

        # Check if "error" is present in the response body (case-insensitive)
        if "error" in response.text.lower():
            return "Potential SQL Injection vulnerability detected"
        return "No SQL Injection vulnerability detected"

    except requests.RequestException as e:
        return f"Error making request: {e}"

# Example usage
url = "https://juice-shop.herokuapp.com/"
result = check_sql_injection(url)
print(result)